name: Deploy API

on:

  push:

    branches:
      - master

jobs:

  deploy:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v4

    - name: Build Image
      run: |
        docker build -t api-node-teste:latest .

    - name: Load image into Kind
      run: |
        kind load docker-image api-node-teste:latest --name lab-fabio

    - name: Deploy
      run: |
        kubectl apply -f k8s/

    - name: Restart Deployment
      run: |
        kubectl -n onecont rollout restart deployment/api-node-teste

    - name: Wait rollout
      run: |
        kubectl -n onecont rollout status deployment/api-node-teste